# Generated by Django 4.2.23 on 2025-07-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(max_length=64)),
                ('version', models.IntegerField()),
                ('uid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=32)),
                ('rate', models.FloatField()),
                ('company_id', models.CharField(max_length=64)),
                ('contractor_id', models.CharField(max_length=64)),
            ],
        ),
    ]
