# Generated by Django 4.2.23 on 2025-07-25 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('id', 'version')},
        ),
    ]
